/run/initialize
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 1 mm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
/detector/nx 50
/detector/ny 40
/detector/xgap 100
/detector/ygap 100
/detector/xpitch 1000
/detector/ypitch 1000
/run/reinitializeGeometry
